.ad l
.TH AMIDE 1 2012-09-20 AMIDE
.SH "NAME"
amide \- AMIDE's a Medical Image Data Examiner
.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
amide \fIinfile\fR ...
.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
AMIDE is a program intended for viewing and analyzing 3D medical imaging 
data sets.
In addition to the program's own internal format (XML Image Format=XIF), 
the program can read in a variety of standard medical file formats using 
the MedCon medical imaging conversion library.  
For a list of the file formats that MedCon supports, please see its manual 
page.  
For additional information on AMIDE, please view the AMIDE help 
documentation, or go to the AMIDE web page: 
<\fBhttp://amide.sourceforge.net\fR>.
.SH "SEE ALSO"
.IX Header "SEE ALSO"
\&\fIgpl\fR\|(7), \&\fImedcon\fR\|(1), \fIxmedcon\fR\|(1)
.SH "BUGS"
.IX Header "BUGS"
Bugs can be reported to the amide user's list 
(amide-users@lists.sourceforge.net).
.SH "AUTHOR"
.IX Header "AUTHOR"
AMIDE was written by Andreas Loening.
For a list of additional contributors, please see the AUTHORS file.
