#undef PACKAGE
#undef VERSION
#undef AMIDE_DEBUG
#undef AMIDE_LIBECAT_SUPPORT
#undef AMIDE_LIBMDC_SUPPORT

#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef ENABLE_NLS
#undef HAVE_GETTEXT
#undef HAVE_CATGETS
