#undef PACKAGE
#undef VERSION
#undef AMIDE_DEBUG
#undef AMIDE_LIBECAT_SUPPORT
#undef AMIDE_LIBMDC_SUPPORT
#undef AMIDE_LIBVOLPACK_SUPPORT
#undef AMIDE_MPEG_ENCODE_SUPPORT
#undef AMIDE_MPEG_ENCODE_BIN
#undef GNOME_XML2_SUPPORT

#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef ENABLE_NLS
#undef HAVE_GETTEXT
#undef HAVE_CATGETS
